### ISSUE TITLE
Locale fr_FR folder is almost empty - Wrong repository

### ISSUE THREAD

**Issue by sylvainraye** [MaWoScha/German_LocalePack_fr_FR#1]
Hi,

Check here https://github.com/MaWoScha/German_LocalePack_fr_FR_/tree/v0.6.2/app/locale/fr_FR
you have two repo for the fr_FR, the previous one looks like to be the correct one. 

Regards
Sylvain

**Comment by MaWoScha** [comment]
I started a new one to fix some problems but because of lack of time I was not able to finish the work.
I try to do it the following days...

**Comment by MaWoScha** [comment]
CSV files added in Version 0.7.0
